server:
  port: 8862

spring:
  application:
    name: service.hi.feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
# Feign默认集成了Ribbon，并和Eureka结合，默认实现了负载均衡的效果。
feign:
  hystrix:
    enabled: true